Add function to get version from package.json
paketo-buildpacks/libnodejs pull request #10
Opened 2023-05-03 01:19 UTC by mhdawson

package_json_parser needs to parse version to be
re-used in npm-install buildpack.

## Summary

Add parsing version in package.json helpers so that shared code
can be reused in npm-install

## Use Cases

reduce duplicated code and centralize knowledge of constants

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2023-05-03 01:32 UTC, mhdawson commented
This is the change to make npm-install use the new functioality. Will submit a PR on paketo-buildpacks/npm-install once this PR lands and there is a new version of libnodejs - https://github.com/mhdawson/npm-install/commit/6a25e53e56dde13e7ad01e42e527d7c8e524877b

2023-05-16 19:40 UTC, mhdawson commented
@thitch97 any chance you could take a look?

2023-05-30 19:56 UTC, TisVictress commented on package_json_test.go
> +			Expect(os.WriteFile(filePath, []byte(`{
@mhdawson Each time the file is written, can it be deleted to keep things clean? (`it.After`)

2023-05-30 19:57 UTC, TisVictress requested changes
Looks fine but I'm worried about lingering files.

2023-05-31 21:10 UTC, mhdawson commented on package_json_test.go
> +			Expect(os.WriteFile(filePath, []byte(`{
Sure will look at doing that in next few days.

2023-06-01 15:27 UTC, mhdawson commented
@TisVictress pushed commit to add cleanup of workingDir after every test.  All files are written to that workingDir so that should makes sure that all files writen are deleted after the test completes.

2023-06-01 15:29 UTC, mhdawson commented on package_json_test.go
> +			Expect(os.WriteFile(filePath, []byte(`{
Pushed commit do do cleanup

2023-06-12 20:07 UTC, mhdawson commented
@TisVictress ping

2023-06-29 15:55 UTC, thitch97 approved these changes

2023-06-29 16:26 UTC, TisVictress approved these changes

2023-06-29 18:25 UTC, merged