move function to find applications into libnodejs
paketo-buildpacks/libnodejs pull request #8
Opened 2023-05-02 17:53 UTC by mhdawson

Move function from to find applications from node-start into libnodejs so that it can be used across buildpacks and extensions.

API has been refined from what was in node-start to make it better as a shared function.

## Summary

Add application finder functionality in node-start to libnodejs so that it can be used
across buildpacks and extensions.

Follow on PRs will
* remove existing functionality in paketo-buildpacks/node-start and make node-start use
the shared function
* remove re-use of function in node-start from paketo-community/ubi-nodejs-extension and
* make ubi-nodejs-extension use the shared function.

Last commit of these branches previews what those PRs will look like once this lands
- https://github.com/mhdawson/node-start/tree/leverage-libnodejs-2[
](https://github.com/mhdawson/node-start/commit/5d6b1527fc238d4891c0824174400b268544fabe)- https://github.com/nodeshift/ubi-nodejs-extension/commit/ce692597f5d2d5d9213f4a43b7b527850ec11ea5

## Use Cases

Reduces duplicate code and centralizes knoweldge of constants

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2023-05-02 18:56 UTC, mhdawson commented
This is a visual diff between the original code in node-start and the new function in libnodejs to show what's re-used which is most of the logic

![image](https://user-images.githubusercontent.com/9373002/235759478-8a3f2aa8-8aa0-403f-a21c-8458d0915e0e.png)

2023-05-16 19:41 UTC, mhdawson commented
@thitch97 any chance you could take a look?

2023-05-30 20:09 UTC, TisVictress commented on find_node_application_test.go
> +		Expect(os.Remove(filepath.Join(workingDir, "server.js"))).To(Succeed())
@mhdawson Maybe each of these should be in its own context where only the scaffolding needed for the test is created and where it can be easily destroyed afterward? This could mean significantly more lines of code but I'm thinking about how this might be confusing to someone reading this or adding tests here in the future.

2023-05-30 20:10 UTC, TisVictress requested changes
Please see my comments; I'm open to discussion.

2023-05-31 21:09 UTC, mhdawson commented on find_node_application_test.go
> +		Expect(os.Remove(filepath.Join(workingDir, "server.js"))).To(Succeed())
I'm happy to adjust if we are ok with having more lines of code. Will look at doing that in next few days.

2023-06-01 16:11 UTC, mhdawson commented
@TisVictress pushed updated version which uses more contexts to avoid removal of files. I agree it is easier/clearer to read what the test is testing and in the end I don't think it ended up being that many more lines of code.

2023-06-12 20:06 UTC, mhdawson commented
@TisVictress ping

2023-06-27 18:07 UTC, thitch97 approved these changes

2023-06-29 18:21 UTC, merged